sudo: required

language: generic

services: 
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t a8975a/reactdocker -f Dockerfile.dev ./

script: 
  - docker run -e CI=true a8975a/reactdocker npm run test -- -- coverage

after_success:
  - echo "Test success"

